In [5]:
import numpy as np

In [6]:
data1=[6, 7, 8.5, 0, 1]

In [7]:
arr1=np.array(data1)

In [8]:
arr1

array([ 6. ,  7. ,  8.5,  0. ,  1. ])

In [9]:
data2=[[1, 2,3,4],[5,6,7,8]]

In [10]:
arr2=np.array(data2)

In [11]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr2.ndim

2

In [13]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [16]:
np.arange(4)

array([0, 1, 2, 3])

In [18]:
arr=np.random.randn(3,6)

In [19]:
arr.T

array([[ 0.63662482, -1.24970507, -1.14981398],
       [ 1.33166964, -1.30716947, -1.15037603],
       [ 1.08537676, -0.13247271, -0.6393511 ],
       [ 0.55882564,  0.79662253,  1.06763534],
       [ 1.10925178, -2.11535338,  0.64294447],
       [-0.42362464, -0.10245375, -0.06707225]])

In [20]:
np.dot(arr.T,arr)

array([[ 3.2891261 ,  3.8040687 ,  1.59166444, -1.86736298,  2.61047852,
        -0.06453237],
       [ 3.8040687 ,  4.80540107,  2.35402175, -1.52533163,  3.50265437,
        -0.35304534],
       [ 1.59166444,  2.35402175,  1.60436157, -0.18158822,  1.07311544,
        -0.4033373 ],
       [-1.86736298, -1.52533163, -0.18158822,  2.08673877, -0.3788296 ,
        -0.38995799],
       [ 2.61047852,  3.50265437,  1.07311544, -0.3788296 ,  6.11853704,
        -0.29630423],
       [-0.06453237, -0.35304534, -0.4033373 , -0.38995799, -0.29630423,
         0.19445329]])

In [23]:
arr=np.array(range(0,8)).reshape(2,4)

In [24]:
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [27]:
arr.transpose()

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [28]:
arr.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [33]:
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [36]:
arr.mean(1)

array([ 1.5,  5.5])

In [37]:
np.random.normal(size=(4,4))

array([[-0.1291322 ,  0.11067895,  0.09153268,  0.21907224],
       [ 0.39784209,  0.62347071, -1.37085013,  0.09461439],
       [ 0.7698248 ,  0.38573823, -1.30544309,  0.74645153],
       [ 1.34275922, -0.27113683,  0.5499618 , -0.41218214]])